/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import Model.Course;
import Model.Lesson;
import java.util.List;
import javax.ejb.Stateless;

/**
 *
 * @author Jeroen Roovers
 */
@Stateless
public class LessonService {

    public LessonService() {
    }

    /**
     * Adds a new lesson with course c, with default values for location and
     * datetime.
     *
     * @param c main course of lesson
     * @return Lesson with id generated by DB
     */
    public Lesson addLesson(Course c) {
        throw new UnsupportedOperationException("Not yet implemented.");
    }

    /**
     * Adds a lesson to the database.
     *
     * @param l new lesson to add
     * @return Lesson with id generated by DB
     */
    public Lesson addLesson(Lesson l) {
        throw new UnsupportedOperationException("Not yet implemented.");
    }

    /**
     * Gets all lessons from the DB
     *
     * @return list of lessons
     */
    public List<Lesson> getLessons() {
        throw new UnsupportedOperationException("Not yet implemented.");
    }

    /**
     * Edits an existing lesson. This method wil update all the fields of a
     * lesson except for the unique identifier 'íd'
     *
     * @param l lesson to be updates
     * @return true if succesful
     */
    public boolean editLesson(Lesson l) {
        throw new UnsupportedOperationException("Not yet implemented.");
    }

    /**
     * Sets an exisiting lesson to inactive. this method will only update the
     * field 'active' of a lesson, based on it's unique identifier 'id'.
     *
     * @param l lessen to be deleted
     * @return true if succesful
     */
    public boolean deleteLesson(Lesson l) {
        throw new UnsupportedOperationException("Not yet implemented.");
    }

}
